name: sencorder
description: A flutter application which record your voice and play it, just like WhatsApp.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  audioplayers: ^3.0.1

  cupertino_icons: ^1.0.5

  flutter:
    sdk: flutter

  flutter_audio_recorder: ^0.5.5

  flutter_secure_storage: ^8.0.0

  get: ^4.6.5

  google_fonts: any

  hive: ^2.2.3

  intl: ^0.18.0

  logger: ^1.3.0

  pedantic: ^1.11.1

  permission_handler: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true